# Generated by Django 2.1.7 on 2021-08-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Coloque o nome do depende', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dependente',
                'verbose_name_plural': 'Dependentes',
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Dev Júnior', 'Dev Júnior'), ('Dev Pleno', 'Dev Pleno'), ('Dev Senior', 'Dev Senior')], max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('VR', models.IntegerField()),
                ('VT', models.IntegerField()),
                ('depen', models.ManyToManyField(blank=True, to='RH.Dependentes')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Plano de Saúde',
                'verbose_name_plural': 'Planos de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe seu nome completo', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='funcao',
            name='nome',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='RH.Registro'),
        ),
        migrations.AddField(
            model_name='funcao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RH.PlanoSaude'),
        ),
    ]
