# Generated by Django 2.1.7 on 2021-07-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(blank=True, db_table='Product', to='clientes.Produto'),
        ),
    ]
